### ISSUE TITLE
Integrate Testing

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/BreweryFinder#28]
Create-react-app ships with Jest. Before implementing CI/CD, this project needs to make use of Jest and implement testing. I will be working on this, but if anyone has experience with testing feel free to jump in.

**Comment by cdrani** [comment]
Tests don't need to be setup before a CI/CD service can be integrated. I'm going to setup travisci this weekend. It will run the one test that we do have and will also deploy an optimized build of the app to gh-pages. This is crucial because I tend to forget to run the build command and push the new changes to gh pages.

**Comment by cdrani** [comment]
Closing this now as testing has been setup and some components already have tests for them.
